### ISSUE TITLE
The problem when test Node SDK

### ISSUE THREAD

**Issue by codeglzhang** [IBM-Blockchain/ibm-blockchain-issues#118]
Hello, I have an Error according to  the tutorial,when I execute `node test/integration/e2e/create-channel.js`.
The error message is as follows：

module.js:471
    throw err;
    ^

Error: Cannot find module './api.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/zhang/go/src/github.com/hyperledger/fabric-sdk-node/node_modules/fabric-ca-client/lib/FabricCAClientImpl.js:19:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

I have been executed `npm install -g gulp` and `npm install`. I don't know how to solve.
Could you help me?

**Comment by dhyey20** [comment]
I think you need to run `gulp ca`.

**Comment by silly-lone-wolf** [comment]
It is useless.I ran `gulp ca` but  it is still wrong.
The error message is as follows：
module.js:471
    throw err;
    ^

Error: Cannot find module 'require-dir'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/zhang/go/src/github.com/hyperledger/fabric-sdk-node/gulpfile.js:6:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by codeglzhang** [comment]
It is OK. Thanks
