### ISSUE TITLE
Cannot access Composer REST server

### ISSUE THREAD

**Issue by EdGrossman** [IBM-Blockchain/ibm-blockchain-issues#120]
Hello,

I'm executing the directions at https://ibm-blockchain.github.io/interacting/ step 4 to run the Composer REST server on Bluemix. The Fabric is up and running; I imported the tutorial business network successfully.  I executed the command 

./create/create_composer-rest-server.sh --business-network-id bluemix-tutorial-net

I am not able to access the server at port 31090. The server is there according to Kubernetes. One thing I noticed is that it does not seem to be picking up the business network name. The container page in Kubernetes shows the environment variable:

COMPOSER_BUSINESS_NETWORK:  org-acme-biznet

and the log for that container (appended to the end of this note) indicates that it keeps trying to find the business network with that name. I tried changing the name in the yaml file but rerunning the create script tells me the server already exists and I don't know how to get around that.

Can you help me debug this please?

Yours truly,
Ed Grossman

>>>>>>>>>>>>>>>>>>>>>>>>>
0|composer | WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.
0|composer | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
0|composer | Discovering types from business network definition ...
0|composer | D1016 21:03:12.993283816    6786 env_linux.c:66]             Warning: insecure environment read function 'getenv' used
0|composer | Connection fails: Error: Error trying to ping. Error: Error trying to query business network. Error: could not find chaincode with name 'org-acme-biznet' - make sure the chaincode org-acme-biznet has been successfully instantiated and try again
0|composer | It will be retried for the next request.
0|composer | Exception: Error: Error trying to ping. Error: Error trying to query business network. Error: could not find chaincode with name 'org-acme-biznet' - make sure the chaincode org-acme-biznet has been successfully instantiated and try again
0|composer | Error: Error trying to ping. Error: Error trying to query business network. Error: could not find chaincode with name 'org-acme-biznet' - make sure the chaincode org-acme-biznet has been successfully instantiated and try again
0|composer |     at _checkRuntimeVersions.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:668:34)
PM2        | App [composer-rest-server] with id [0] and pid [6786], exited with code [1] via signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:composer-rest-server id:0
PM2        | App name:composer-rest-server id:0 online
0|composer | WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.
0|composer | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
0|composer | Discovering types from business network definition ...
0|composer | D1016 21:03:18.720968991    6799 env_linux.c:66]             Warning: insecure environment read function 'getenv' used
0|composer | Connection fails: Error: Error trying to ping. Error: Error trying to query business network. Error: could not find chaincode with name 'org-acme-biznet' - make sure the chaincode org-acme-biznet has been successfully instantiated and try again
0|composer | It will be retried for the next request.
0|composer | Exception: Error: Error trying to ping. Error: Error trying to query business network. Error: could not find chaincode with name 'org-acme-biznet' - make sure the chaincode org-acme-biznet has been successfully instantiated and try again
0|composer | Error: Error trying to ping. Error: Error trying to query business network. Error: could not find chaincode with name 'org-acme-biznet' - make sure the chaincode org-acme-biznet has been successfully instantiated and try again
0|composer |     at _checkRuntimeVersions.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:668:34)
PM2        | App [composer-rest-server] with id [0] and pid [6799], exited with code [1] via signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:composer-rest-server id:0
PM2        | App name:composer-rest-server id:0 online
0|composer | WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.
0|composer | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
0|composer | Discovering types from business network definition ...
0|composer | D1016 21:03:23.739640241    6812 env_linux.c:66]             Warning: insecure environment read function 'getenv' used

**Comment by EdGrossman** [comment]
Sorry - I discovered I was using old scripts
