### ISSUE TITLE
Installing the Hypeledger Fabric on Windows

### ISSUE THREAD

**Issue by junaid-khurshid** [IBM-Blockchain/ibm-blockchain-issues#122]

**Comment by junaid-khurshid** [comment]
I have gone through all the Prerequisites as mentioned in Hyperledger docs official and installed all them in my Window 10 , then I want to confirm is it installed properly i ran runApp.sh from balance-transfer on docker then the server started after that i run testAPI.sh from balance-transfer on Git-bash but i am getting error below : 

[2018-01-27 11:27:31.070] [ERROR] Helper - Error: Calling enrollment endpoint failed with error [Error: connect ECONNREFUSED 127.0.0.1:8054]
    at ClientRequest.<anonymous> (F:\HyperLegderFabric\fabric-samples\balance-transfer\node_modules\fabric-ca-client\lib\FabricCAClientImpl.js:711:12)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[2018-01-27 11:27:31.079] [DEBUG] Helper - Barry failed to register
[2018-01-27 11:27:31.084] [ERROR] Helper - Barry enrollment failed
(node:9888) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Cannot save null userContext.
(node:9888) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: Cannot read property '_enrollmentSecret' of null 

is it someting my port error?? or something else..
if anyone had properly installed on Windows can help me out...  :)
