### ISSUE TITLE
When enrolling: "Error: Identity lookup error: sql: no rows in result set"

### ISSUE THREAD

**Issue by MrBuggySan** [IBM-Blockchain/ibm-blockchain-issues#67]
Hi I'm looking through this sample hfc tutorial https://console.au-syd.bluemix.net/docs/services/blockchain/etn_sdk.html#nodesample and I'm running the Blockchain service in bluemix. 

I have have separated the register and enroll process like this code spnippet instead of using the default chain.registerAndEnroll() :

```
       var registrationRequest = {
            enrollmentID: "ElPerro",
            name: "ElGato",
            account: "group1",
            affiliation: "00001"
        };
        console.log("Now registering: " + registrationRequest.name);
        chain.register(registrationRequest, function(err, enrollmentSecret) {
            if (err) {
                throw Error("Failed to register " + registrationRequest.name + ": " + err);
            }
            console.log("Succesfully registered " + registrationRequest.name);
            registrationRequest.enrollmentSecret = enrollmentSecret;
            //At this point, 'registration' only enables this person to enroll

            console.log("Now enrolling: " + registrationRequest.name);
            chain.enroll(registrationRequest.name, registrationRequest.enrollmentSecret,
                function(err, member) {
                    if (err) {
                        throw Error("Failed to enroll " + registrationRequest.name + ": " + err);
                    }

                    //A member object is returned 
                    console.log(member);
                    console.log("Succesfully enrolled " + registrationRequest.name);
                }
            );
        });
```

I am getting this error, any tips on what to do here? 

```
Error: Failed to enroll Buiza2: Error: Identity lookup error: sql: no rows in result set
    at Error (native)
    at /home/andreibuiza/SchoolCode/capstone/HFCofficialTEST/BlockVoteNode/app.js:262:23
    at /home/andreibuiza/SchoolCode/capstone/HFCofficialTEST/BlockVoteNode/node_modules/hfc/lib/hfc.js:468:28
    at /home/andreibuiza/SchoolCode/capstone/HFCofficialTEST/BlockVoteNode/node_modules/hfc/lib/hfc.js:718:24
    at Object.callback (/home/andreibuiza/SchoolCode/capstone/HFCofficialTEST/BlockVoteNode/node_modules/hfc/lib/hfc.js:1898:24)
    at /home/andreibuiza/SchoolCode/capstone/HFCofficialTEST/BlockVoteNode/node_modules/grpc/src/node/src/client.js:420:14
`
```

**Comment by masterDev1985** [comment]
@MrBuggySan you should use the `enrollmentID` parameter instead of the `name` parameter to reference your registered user when trying to enroll that user.  I don't think `name` gets used for anything.

See here:
https://github.com/IBM-Blockchain/SDK-Demo/blob/master/helloblockchain.js#L153

**Comment by MrBuggySan** [comment]
@masterDev1985 yes you are right! I must have mixed up the two... Thank you:)

**Comment by ssaddem** [comment]
delete your keyValStore i think tha you have changed from the peer host
