### ISSUE TITLE
Broken pipe on invoke (but deploy is working)

### ISSUE THREAD

**Issue by arner** [IBM-Blockchain/ibm-blockchain-issues#76]
Hi,

I'm migrating from 0.5 to 0.6.1. Locally everything works. Deployment of chaincode to bluemix also works fine, but when I try to do an invoke 5 minutes later I get an error.

The network id is 01a33d6f5783438ea22a04fd89e60bf7. I tried deleting it and starting a new one, same error.

Not sure if it's related but the only warning I get is:

 hfc [memberServices.enroll] Unmarshalling chainKey +1ms
  hfc Warning: problem parsing certificate bytes; retrying ...  +656ms RangeError: byte length of Uint32Array should be a multiple of 4
    at new Uint32Array (native)
    at in_window.org.pkijs.asn1.UNIVERSALSTRING.fromBuffer (/Users/arne/dev/torch/node_modules/asn1js/org/pkijs/asn1.js:3438:66)
    at in_window.org.pkijs.asn1.UNIVERSALSTRING.fromBER (/Users/arne/dev/torch/node_modules/asn1js/org/pkijs/asn1.js:3407:71)
    at fromBER_raw (/Users/arne/dev/torch/node_modules/asn1js/org/pkijs/asn1.js:4968:39)
    at Object.in_window.org.pkijs.fromBER (/Users/arne/dev/torch/node_modules/asn1js/org/pkijs/asn1.js:4998:16)
    at in_window.org.pkijs.simpl.EXTENSION.fromSchema (/Users/arne/dev/torch/node_modules/pkijs/org/pkijs/x509_simpl.js:3636:36)
    at new in_window.org.pkijs.simpl.EXTENSION (/Users/arne/dev/torch/node_modules/pkijs/org/pkijs/x509_simpl.js:3589:70)
    at in_window.org.pkijs.simpl.CERT.fromSchema (/Users/arne/dev/torch/node_modules/pkijs/org/pkijs/x509_simpl.js:3939:38)
    at new in_window.org.pkijs.simpl.CERT (/Users/arne/dev/torch/node_modules/pkijs/org/pkijs/x509_simpl.js:3855:65)
    at new X509Certificate (/Users/arne/dev/torch/node_modules/hfc/lib/crypto.js:475:26)
  hfc Warning: problem parsing certificate bytes; retrying ...  +316ms Error: Wrong input string for convertion
    at in_window.org.pkijs.asn1.GENERALIZEDTIME.fromString (/Users/arne/dev/torch/node_modules/asn1js/org/pkijs/asn1.js:4214:23)
    at in_window.org.pkijs.asn1.GENERALIZEDTIME.fromBuffer (/Users/arne/dev/torch/node_modules/asn1js/org/pkijs/asn1.js:4145:71)
    at in_window.org.pkijs.asn1.GENERALIZEDTIME.fromBER (/Users/arne/dev/torch/node_modules/asn1js/org/pkijs/asn1.js:4128:71)
    at fromBER_raw (/Users/arne/dev/torch/node_modules/asn1js/org/pkijs/asn1.js:4968:39)
    at Object.in_window.org.pkijs.fromBER (/Users/arne/dev/torch/node_modules/asn1js/org/pkijs/asn1.js:4998:16)
    at in_window.org.pkijs.simpl.EXTENSION.fromSchema (/Users/arne/dev/torch/node_modules/pkijs/org/pkijs/x509_simpl.js:3636:36)
    at new in_window.org.pkijs.simpl.EXTENSION (/Users/arne/dev/torch/node_modules/pkijs/org/pkijs/x509_simpl.js:3589:70)
    at in_window.org.pkijs.simpl.CERT.fromSchema (/Users/arne/dev/torch/node_modules/pkijs/org/pkijs/x509_simpl.js:3939:38)
    at new in_window.org.pkijs.simpl.CERT (/Users/arne/dev/torch/node_modules/pkijs/org/pkijs/x509_simpl.js:3855:65)
    at new X509Certificate (/Users/arne/dev/torch/node_modules/hfc/lib/crypto.js:475:26)
  hfc Got a TCert successfully, continue... +353ms

After this, the flow continues and the deployment is executed successfully.

Finally, at the invoke:

  hfc peer.sendTransaction: error={"message":"{\"created\":\"@1480505750.881737000\",\"description\":\"OS Error\",\"errno\":32,\"file\":\"../src/core/lib/iomgr/tcp_posix.c\",\"file_line\":340,\"os_error\":\"Broken pipe\",\"syscall\":\"sendmsg\"}","stack":"Error: {\"created\":\"@1480505750.881737000\",\"description\":\"OS Error\",\"errno\":32,\"file\":\"../src/core/lib/iomgr/tcp_posix.c\",\"file_line\":340,\"os_error\":\"Broken pipe\",\"syscall\":\"sendmsg\"}\n    at /Users/arne/dev/torch/node_modules/grpc/src/node/src/client.js:417:17","code":13,"metadata":{"_internal_repr":{}}} +3ms

Thanks!

**Comment by arner** [comment]
Apparently there was an issue with the blockchain network which is now resolved.
