### ISSUE TITLE
gRPC error? 

### ISSUE THREAD

**Issue by MrBuggySan** [IBM-Blockchain/ibm-blockchain-issues#84]
I'm trying to run the HFC tutorial: https://console.ng.bluemix.net/docs/services/blockchain/etn_sdk.html

I tried re-doing npm install a couple of times and making a new blockchain service on Bluemix but it is still not successful. 

```
Enrolled admin sucecssfully
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error
    at ClientDuplexStream._emitStatusIfDone (F:\Documents\CapstoneCode\HFCprac\SDK-Demo\node_modules\grpc\src\node\src\client.js:189:19)
    at ClientDuplexStream._readsDone (F:\Documents\CapstoneCode\HFCprac\SDK-Demo\node_modules\grpc\src\node\src\client.js:158:8)
    at readCallback (F:\Documents\CapstoneCode\HFCprac\SDK-Demo\node_modules\grpc\src\node\src\client.js:217:12)
```

Anyone else have this error going on with their applications?

**Comment by mastersingh24** [comment]
in your BMX service credentials, what is the port number being used for events?

**Comment by mastersingh24** [comment]
@MrBuggySan  -  the problem is with the connection to the eventhub.  The easiest thing to do to get past this is to simply comment out all references to "eventhub" in `helloblockchain.js`

**Comment by dhyey20** [comment]
Closing this due to inactivity. If you are seeing the events related problems, feel free to re-open.
